### ISSUE TITLE
Error: Error loading Interface XML file: cgra_array_add_interface.xml and Assertion `NumContainedTys && "Attempting to get element type of opaque pointer"' failed

### ISSUE THREAD

**Issue by neulxf** [ecolab-nus/morpher-v2#1]
Hello
I followed README's instructions to configure the environment, but there is an error at runtime that shows a load Interface XML file error, and I wasn't able to find out from the source code where this file is generated.
The second problem was an ASSERTION FAILED in the opt.
Looking forward to your reply.
![image](https://github.com/ecolab-nus/morpher-v2/assets/100358779/07c23afc-a59c-4387-a461-1bfd67e0173a)
![image](https://github.com/ecolab-nus/morpher-v2/assets/100358779/9c6ea0d6-355f-4716-b4f5-c2502f4bdeed)

**Comment by Marita-loves-Foxes** [comment]
I was able to get rid of the assert-problem by building llvm with the flag
`-DCLANG_ENABLE_OPAQUE_POINTERS=OFF`.

Here is the complete command I used:
```
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=TRUE -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_ENABLE_PROJECTS='polly;clang' -DCLANG_ENABLE_OPAQUE_POINTERS=OFF ../llvm
```

**Comment by neulxf** [comment]
Thanks for your reply, I gave it a try, and your suggestion does work. Thank you very much！
